# Input data {.unnumbered}

> **Summary**. Global parameters were taken from @schmitt2024. Taxonomy and maximum diameter were taken from LBA inventories. Allometric height parameters were inferred from TALLO [@jucker2022], and leaf, wood, and hydraulic traits were taken from @schmitt2024, TRY [@kattge2019], and BIOMASS [@réjou-méchain2017]. Missing traits were imputed using `missForest` with phylogeny [@gendre2024]. Soil parameters were also taken from @schmitt2024. Historical climate forcing from ERA5-Land between 1980 and 2025 was used as it showed a good correlation with local measurements. Future climate forcing was obtained from CMIP6 GCMs between 1980 and 2100 under low-emission scenarios SSP1-2.6 and high-emission scenarios SSP5-8.5 [@neill2016]. The daily values from the CMIP6 GCMs were statistically corrected for bias using the daily values of the ERA5-Land historical dataset via a cumulative distribution function transformation (CDFt; \@vrac2015). This was done independently for each month to preserve the seasonal variations. The daily values from the CMIP6 GCMs were then statistically downscaled to half-hourly values using the daily mean variations from the half-hourly ERA5-Land values across years.
