project:
  type: book
  output-dir: docs

book:
  title: "TROLL TEE"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - part: 10_data.qmd
      chapters: 
        - 11_species.qmd
        - 12_climate.qmd
        - 13_soil.qmd
        - 14_forest.qmd
        - 15_fluxes.qmd
        - 16_microclimate.qmd
    - part: 20_experiments.qmd
      chapters: 
        - 21_dummy.qmd
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
